### ISSUE TITLE
How to use it in Openhab2?

### ISSUE THREAD

**Issue by stratopause** [octa22/org.openhab.binding.yeelight#1]

**Comment by schmieeed** [comment]
copy the zip file to the /adds folder. Now it should be listed in UI -> Configuration -> Bindings.
The "LAN Control" need to be enabled via the Yeelight App!

**Comment by tloers** [comment]
Hi everybody. Did like mentioned above. After reboot I can see the binding with possible things in it. I am aiming for the led color bulb.
I switched bulb on/off several times, and even "LAN Control" on/off several times. But it won't show in the Inbox.
Any suggestions?
thank you in advance!

**Comment by octa22** [comment]
Hi, look at your openhab.log file and see if there are some detected devices. Add them manually to items file as mentioned in readme.md (you need only thing´s IP address)
Things auto discovery in UI doesn’t work for OH1.X bindings...
